* Naim's Website

This is my personal website repository. I'm using =emacs= and =org-mode= to create this
website.

** Installation guide

For Windows operating system, it is recommended to have =cholocatey= package
manager comes pre-install in the system before proceeding to the next step. If
=cholocatey= package manager have already installed, execute the following
command to install =GNU Make= application to simplify the publishing process.

#+begin_src shell
choco install make
#+end_src

It is also recommended to install =emacs= via =cholocatey= package manager by
executing the command below. By doing so, I believe it will automatically add
=emacs= command into Environment Variables.

#+begin_src shell
choco install emacs
#+end_src

However, if you install it manually or =chocolatey= package manager somehow
skipped it, you must add the following path =C:\Program Files\Emacs\x86_64\bin=
or similar path depending on the architecture chosen into User Variables under
variable called path. This is required for Makefile to be executed successfully.

** Development guide

To begin developing the website, you must first clone the repository by
executing the following command:

#+begin_src shell
git clone https://github.com/NaimJamalludin/NaimJamalludin.github.io.git
#+end_src

All changes should be done in =src= folder.

** Publish guide

To publish the website from =org-mode=, simply open your terminal and execute
the following command:

#+begin_src shell
make
#+end_src

This will create html files located in =public= folder.
