#+TITLE: About Me
#+DESCRIPTION: About me
#+AUTHOR: Naim Jamalludin
#+DATE: <2021-07-24 Sat>
#+HTML_LINK_UP: ../index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/style.css" />
#+OPTIONS: num:nil toc:nil html-postamble:nil

** About myself

My name is Naim Jamalludin. I'm a software engineer based in Kuala Lumpur,
Malaysia. You can also find me on:

1. [[https://github.com/NaimJamalludin][Github]]
2. [[https://stackoverflow.com/users/5597716/naim-jamalludin?tab=profile][StackOverflow]]

This website is created using =emacs= and =org-mode=. You may find
the source code over [[https://github.com/NaimJamalludin/NaimJamalludin.github.io][here]].

** Disclaimer

This is a personal website. Any views or opinions represented in this site are
personal and belong solely to the site owner and do not represent those of
people, institutions or organizations that the owner may or may not be
associated with in professional or personal capacity, unless explicitly stated.

Any views or opinions are not intended to malign any religion, ethnic group,
club, organization, company, or individual.

All content provided on this website is for informational purposes only. The owner
of this website makes no representations as to the accuracy or completeness of any
information on this site or found by following any link on this site.

The owner will not be liable for any errors or omissions in this information nor
for the availability of this information. The owner will not be liable for any
losses, injuries, or damages from the display or use of this information.
